version: "3.9"
services:

  vehicle_app:
    build: .
    restart: always
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8525
    expose:
      - 8525
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 81:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      #- ./fromdockernginxM.conf:/etc/nginx/conf.d/default.conf
    #volumes:
      #- ./fromdockernginxM.conf:/etc/nginx/conf.d/default.conf
      #- ./default.conf:/etc/nginx/conf.d/defaulti.conf
    #volumes:
      #- ./nginx.conf:/root/ProjectCars/nginx.conf
    #volumes:
      #- ./nginx.conf:/root/ProjectCars/fromdockernginx.conf
    depends_on:
      - vehicle_app

  postgres:
    image: postgres:14.8-alpine3.18
    command:
      - "postgres"
      - "-c"
      - "max_connections=2000"
      - "-c"
      - "shared_buffers=2GB"
      - "-c"
      - "effective_cache_size=6GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=1GB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=1s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - 'work_mem=262kB'
      - "-c"
      - 'huge_pages=off'
      - "-c"
      - 'min_wal_size=4GB'
      - "-c"
      - 'max_wal_size=16GB'
      - "-c"
      - 'max_worker_processes=4'
      - "-c"
      - 'max_parallel_workers_per_gather=2'
      - "-c"
      - 'max_parallel_workers=4'
      - "-c"
      - 'max_parallel_maintenance_workers=2'
      
    environment:
      POSTGRES_DB: "vehdatabase"
      POSTGRES_USER: "vehuser"
      POSTGRES_PASSWORD: "vehpassword"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: always
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - habrdb-data:/var/lib/postgresql/data
    ports:
      - "5434:5434"
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: vincente_del_puhini
    ports:
      - "5051:80"
    depends_on:
      - postgres
volumes:
  habrdb-data:
  cache:
    driver: local
