services:
  my_redis:
    image: redis:alpine
    container_name: my_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - app_network


  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: my_app
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      my_redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://my_redis:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge